[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lift"
version = "0.0.1"
description = "LIFT - Logistics & Infrastructure Fleet Transformation"
authors = [
    { name = "Anna Paper", email = "anna.paper@tum.de" },
    { name = "Fabian Mayer", email = "fabian.mayer@tum.de" },
    { name = "Brian Dietermann", email = "brian.dietermann@tum.de"}
]

readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib",
    "streamlit",
]

[tool.setuptools]
packages = ["lift"]

# [tool.setuptools.package-data]
# lift = ["data/*", "example/*"]

[project.scripts]
lift = "lift.main:main"
